version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: serpent-db.cstiwmk8m9ja.us-east-1.rds.amazonaws.com
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
      MYSQL_DATABASE: serpent_surge_db
      PORT: 5000
   
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
